export interface FarmerService {
  id: string
  title: string
  category: string
  categoryEmoji: string
  price: string
  description: string
  rating: number
  availability: string
  verified: boolean
  providersNearby?: number
  arrivalTime?: string
  jobsCompleted?: number
  image?: string
  features?: string[]
}

export const serviceCategories = [
  { id: 'all', label: 'All', emoji: '🔥' },
  { id: 'popular', label: 'Popular', emoji: '⭐' },
  { id: 'technology', label: 'Technology', emoji: '🚁' },
  { id: 'machinery', label: 'Machinery', emoji: '🚜' },
  { id: 'advisory', label: 'Crop Care', emoji: '🌱' },
  { id: 'irrigation', label: 'Irrigation', emoji: '💧' },
  { id: 'labour', label: 'Labour', emoji: '👨‍🌾' },
  { id: 'logistics', label: 'Transport', emoji: '🚛' },
  { id: 'inputs', label: 'Inputs', emoji: '🛒' },
  { id: 'infrastructure', label: 'Infrastructure', emoji: '🏡' },
]

export const farmerServices: FarmerService[] = [
  // Technology Services
  {
    id: 'drone-spraying',
    title: 'Drone Spraying',
    category: 'technology',
    categoryEmoji: '🚁',
    price: '₹800 / acre',
    description: 'AI-powered precision pesticide spraying',
    rating: 4.9,
    availability: 'Available Today',
    verified: true,
    providersNearby: 12,
    arrivalTime: '45 mins',
    jobsCompleted: 1250,
    features: ['GPS Tracked', 'Verified Operator', 'Insured', '24×7 Support']
  },
  {
    id: 'crop-disease-detection',
    title: 'AI Crop Disease Detection',
    category: 'technology',
    categoryEmoji: '🚁',
    price: '₹99 / diagnosis',
    description: 'Upload crop photo and get instant disease detection',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 50,
    jobsCompleted: 3420,
    features: ['95%+ Accuracy', 'Instant Results', 'Treatment Plan', 'Follow-up Support']
  },
  {
    id: 'soil-testing',
    title: 'Soil Testing',
    category: 'technology',
    categoryEmoji: '🚁',
    price: '₹399 / sample',
    description: 'Know soil nutrients, pH and fertilizer recommendation',
    rating: 4.9,
    availability: 'Available Tomorrow',
    verified: true,
    providersNearby: 8,
    arrivalTime: '1 day',
    jobsCompleted: 890,
    features: ['Lab Certified', 'Detailed Report', 'Recommendations', 'Free Consultation']
  },
  {
    id: 'farm-mapping',
    title: 'Farm Mapping',
    category: 'technology',
    categoryEmoji: '🚁',
    price: '₹499 / farm',
    description: 'GPS boundary mapping and acreage measurement',
    rating: 4.7,
    availability: 'Available Today',
    verified: true,
    providersNearby: 5,
    arrivalTime: '2 hours',
    jobsCompleted: 456,
    features: ['GPS Accurate', 'Digital Map', 'Export Options', 'Legal Compliance']
  },
  {
    id: 'smart-irrigation',
    title: 'Smart Irrigation Planning',
    category: 'technology',
    categoryEmoji: '🚁',
    price: '₹299 / farm',
    description: 'AI irrigation schedule based on weather',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 25,
    jobsCompleted: 2100,
    features: ['Weather Integrated', 'Soil Moisture', 'Cost Saving', 'Real-time Updates']
  },
  {
    id: 'satellite-monitoring',
    title: 'Satellite Crop Monitoring',
    category: 'technology',
    categoryEmoji: '🚁',
    price: '₹999 / month',
    description: 'Monitor crop health using satellite imagery',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 1,
    jobsCompleted: 650,
    features: ['Real-time Updates', 'Health Score', 'Yield Prediction', 'Early Alerts']
  },

  // Machinery Services
  {
    id: 'tractor-booking',
    title: 'Tractor Booking',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹600 / hour',
    description: 'Ploughing, rotavator, cultivator services',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 18,
    arrivalTime: '1 hour',
    jobsCompleted: 5620,
    features: ['Experienced Operator', 'Fuel Included', 'On-time Guarantee', 'Insurance']
  },
  {
    id: 'rotavator',
    title: 'Rotavator Service',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹900 / acre',
    description: 'Land preparation for sowing',
    rating: 4.9,
    availability: 'Available Today',
    verified: true,
    providersNearby: 14,
    arrivalTime: '2 hours',
    jobsCompleted: 4230,
    features: ['Deep Tilling', 'Weed Control', 'Soil Mixing', 'Quality Assured']
  },
  {
    id: 'seed-drill',
    title: 'Seed Drill Machine',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹700 / acre',
    description: 'Uniform seed sowing with precision',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 10,
    arrivalTime: '1.5 hours',
    jobsCompleted: 3120,
    features: ['Uniform Spacing', 'Seed Saving', 'Reduced Labor', 'Increased Yield']
  },
  {
    id: 'paddy-transplanter',
    title: 'Paddy Transplanter',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹1,500 / acre',
    description: 'Faster paddy transplantation',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 8,
    arrivalTime: '3 hours',
    jobsCompleted: 1850,
    features: ['Time Saving', 'Labor Reduction', 'Better Spacing', 'Higher Output']
  },
  {
    id: 'combine-harvester',
    title: 'Combine Harvester',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹1,200 / acre',
    description: 'Efficient harvesting with operators',
    rating: 4.7,
    availability: 'Available Today',
    verified: true,
    providersNearby: 6,
    arrivalTime: '4 hours',
    jobsCompleted: 2560,
    features: ['Fast Harvesting', 'Minimal Loss', 'Clean Grain', 'Expert Operator']
  },
  {
    id: 'reaper-machine',
    title: 'Reaper Machine',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹900 / acre',
    description: 'Crop cutting service',
    rating: 4.7,
    availability: 'Available Today',
    verified: true,
    providersNearby: 9,
    arrivalTime: '2.5 hours',
    jobsCompleted: 1920,
    features: ['Clean Cutting', 'Stalk Binding', 'Labor Saving', 'Quality Output']
  },
  {
    id: 'happy-seeder',
    title: 'Happy Seeder',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹1,000 / acre',
    description: 'Direct sowing after harvest',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 7,
    arrivalTime: '2 hours',
    jobsCompleted: 1450,
    features: ['No Tillage', 'Cost Saving', 'Time Saving', 'Residue Management']
  },
  {
    id: 'straw-baler',
    title: 'Straw Baler',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹850 / acre',
    description: 'Collect crop residue efficiently',
    rating: 4.6,
    availability: 'Available Today',
    verified: true,
    providersNearby: 5,
    arrivalTime: '3 hours',
    jobsCompleted: 980,
    features: ['Residue Collection', 'Easy Transport', 'Extra Income', 'Farm Clean']
  },
  {
    id: 'power-weeder',
    title: 'Power Weeder',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹650 / acre',
    description: 'Weed removal without chemicals',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 11,
    arrivalTime: '1.5 hours',
    jobsCompleted: 3890,
    features: ['Chemical Free', 'Soil Aeration', 'Labor Saving', 'Organic Farming']
  },
  {
    id: 'laser-leveler',
    title: 'Laser Land Leveler',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹1,100 / acre',
    description: 'Precision land leveling',
    rating: 4.9,
    availability: 'Available Today',
    verified: true,
    providersNearby: 4,
    arrivalTime: '2 hours',
    jobsCompleted: 750,
    features: ['Precision Accuracy', 'Water Saving', 'Better Yield', 'Tech Advanced']
  },
  {
    id: 'mini-tractor',
    title: 'Mini Tractor',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹500 / hour',
    description: 'Ideal for small farms',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 16,
    arrivalTime: '1 hour',
    jobsCompleted: 4560,
    features: ['Flexible Use', 'Affordable', 'Fuel Efficient', 'Easy Operation']
  },
  {
    id: 'excavator',
    title: 'Excavator (JCB)',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹1,600 / hour',
    description: 'Farm leveling and pond excavation',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 3,
    arrivalTime: '4 hours',
    jobsCompleted: 420,
    features: ['Heavy Lifting', 'Precision Work', 'Expert Operator', 'Full Insurance']
  },
  {
    id: 'borewell-drilling',
    title: 'Borewell Drilling',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: 'Custom Quote',
    description: 'Groundwater drilling service',
    rating: 4.7,
    availability: 'Available Today',
    verified: true,
    providersNearby: 2,
    jobsCompleted: 180,
    features: ['Professional Drilling', 'Water Testing', 'Legal Compliance', 'Warranty']
  },
  {
    id: 'earth-mover',
    title: 'Earth Mover',
    category: 'machinery',
    categoryEmoji: '🚜',
    price: '₹1,800 / hour',
    description: 'Farm infrastructure works',
    rating: 4.7,
    availability: 'Available Today',
    verified: true,
    providersNearby: 2,
    arrivalTime: '5 hours',
    jobsCompleted: 320,
    features: ['Large Scale', 'Infrastructure Ready', 'Expert Crew', 'Project Managed']
  },

  // Crop Advisory
  {
    id: 'agriculture-consultant',
    title: 'Agriculture Expert Consultation',
    category: 'advisory',
    categoryEmoji: '🌱',
    price: '₹199 / session',
    description: 'Video or phone consultation',
    rating: 4.9,
    availability: 'Available Now',
    verified: true,
    providersNearby: 30,
    jobsCompleted: 8900,
    features: ['Expert Advice', 'Personalized', 'Phone/Video', 'Follow-up Support']
  },
  {
    id: 'fertilizer-recommendation',
    title: 'Fertilizer Recommendation',
    category: 'advisory',
    categoryEmoji: '🌱',
    price: 'Free',
    description: 'Based on crop and soil',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 40,
    jobsCompleted: 12500,
    features: ['Custom Formula', 'Soil Based', 'Cost Optimized', 'No Commitment']
  },
  {
    id: 'pest-management',
    title: 'Pest Management',
    category: 'advisory',
    categoryEmoji: '🌱',
    price: '₹149',
    description: 'Expert pest control guidance',
    rating: 4.9,
    availability: 'Available Now',
    verified: true,
    providersNearby: 35,
    jobsCompleted: 7800,
    features: ['Organic Options', 'Cost Effective', 'Environment Safe', 'Proven Results']
  },
  {
    id: 'crop-planning',
    title: 'Crop Planning',
    category: 'advisory',
    categoryEmoji: '🌱',
    price: '₹299',
    description: 'Best crops for your land',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 25,
    jobsCompleted: 4200,
    features: ['Market Analysis', 'Risk Assessment', 'Revenue Forecast', 'Detailed Plan']
  },
  {
    id: 'organic-farming',
    title: 'Organic Farming Guide',
    category: 'advisory',
    categoryEmoji: '🌱',
    price: '₹199',
    description: 'Natural farming assistance',
    rating: 4.7,
    availability: 'Available Now',
    verified: true,
    providersNearby: 20,
    jobsCompleted: 3100,
    features: ['Certification Help', 'Techniques', 'Market Links', 'Premium Pricing']
  },
  {
    id: 'weather-advisory',
    title: 'Weather Advisory',
    category: 'advisory',
    categoryEmoji: '🌱',
    price: 'Free',
    description: 'Hyperlocal weather alerts',
    rating: 4.9,
    availability: 'Available Now',
    verified: true,
    providersNearby: 100,
    jobsCompleted: 50000,
    features: ['Real-time Updates', 'Hyperlocal', 'Early Warnings', 'Actionable Tips']
  },
  {
    id: 'government-schemes',
    title: 'Government Schemes Help',
    category: 'advisory',
    categoryEmoji: '🌱',
    price: 'Free',
    description: 'Apply for subsidies easily',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 45,
    jobsCompleted: 6700,
    features: ['Form Filling', 'Documentation', 'Approval Tracking', 'Success Assured']
  },
  {
    id: 'crop-insurance',
    title: 'Crop Insurance Assistance',
    category: 'advisory',
    categoryEmoji: '🌱',
    price: 'Free',
    description: 'Insurance claim support',
    rating: 4.7,
    availability: 'Available Now',
    verified: true,
    providersNearby: 32,
    jobsCompleted: 5400,
    features: ['Claim Processing', 'Document Help', 'Fast Settlement', 'Higher Payouts']
  },

  // Irrigation Services
  {
    id: 'drip-irrigation',
    title: 'Drip Irrigation Installation',
    category: 'irrigation',
    categoryEmoji: '💧',
    price: 'Custom Quote',
    description: 'Water-saving irrigation system',
    rating: 4.9,
    availability: 'Available Today',
    verified: true,
    providersNearby: 8,
    jobsCompleted: 1200,
    features: ['Water Saving', 'Government Subsidy', 'Expert Installation', 'Warranty']
  },
  {
    id: 'sprinkler-installation',
    title: 'Sprinkler Installation',
    category: 'irrigation',
    categoryEmoji: '💧',
    price: 'Custom Quote',
    description: 'Efficient irrigation setup',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 10,
    jobsCompleted: 980,
    features: ['Even Distribution', 'Labor Saving', 'Energy Efficient', 'Low Maintenance']
  },
  {
    id: 'solar-pump',
    title: 'Solar Pump Installation',
    category: 'irrigation',
    categoryEmoji: '💧',
    price: 'Custom Quote',
    description: 'Government subsidy available',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 6,
    jobsCompleted: 450,
    features: ['Govt Subsidy', 'Free Energy', 'Eco Friendly', 'Long Life']
  },
  {
    id: 'motor-repair',
    title: 'Bore Motor Repair',
    category: 'irrigation',
    categoryEmoji: '💧',
    price: '₹599',
    description: 'On-site technician',
    rating: 4.7,
    availability: 'Available Today',
    verified: true,
    providersNearby: 12,
    arrivalTime: '1 hour',
    jobsCompleted: 2340,
    features: ['Quick Fix', 'Quality Parts', 'Warranty', '24×7 Available']
  },

  // Labour Services
  {
    id: 'farm-labour',
    title: 'Farm Labour Booking',
    category: 'labour',
    categoryEmoji: '👨‍🌾',
    price: '₹700 / worker',
    description: 'Skilled agricultural workers',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 50,
    jobsCompleted: 15600,
    features: ['Verified Workers', 'Insurance', 'Timely Arrival', 'Task Completion']
  },
  {
    id: 'harvest-labour',
    title: 'Harvest Labour',
    category: 'labour',
    categoryEmoji: '👨‍🌾',
    price: '₹800 / worker',
    description: 'Crop harvesting support',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 45,
    jobsCompleted: 12800,
    features: ['Experienced Team', 'Quick Harvest', 'Quality Work', 'Fair Wages']
  },
  {
    id: 'plantation-labour',
    title: 'Plantation Labour',
    category: 'labour',
    categoryEmoji: '👨‍🌾',
    price: '₹650 / worker',
    description: 'Seedling plantation assistance',
    rating: 4.7,
    availability: 'Available Today',
    verified: true,
    providersNearby: 35,
    jobsCompleted: 8900,
    features: ['Skilled Staff', 'Fast Planting', 'Proper Spacing', 'High Survival Rate']
  },
  {
    id: 'irrigation-worker',
    title: 'Irrigation Worker',
    category: 'labour',
    categoryEmoji: '👨‍🌾',
    price: '₹600 / day',
    description: 'Water management services',
    rating: 4.7,
    availability: 'Available Today',
    verified: true,
    providersNearby: 40,
    jobsCompleted: 6700,
    features: ['Water Expert', 'Regular Maintenance', 'Efficient Watering', 'Cost Save']
  },

  // Logistics
  {
    id: 'crop-transportation',
    title: 'Crop Transportation',
    category: 'logistics',
    categoryEmoji: '🚛',
    price: '₹1,500 / trip',
    description: 'Farm to market delivery',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 20,
    jobsCompleted: 4500,
    features: ['Insured Transport', 'Quick Delivery', 'Safe Handling', 'Fair Pricing']
  },
  {
    id: 'cold-storage',
    title: 'Cold Storage Booking',
    category: 'logistics',
    categoryEmoji: '🚛',
    price: '₹2 / kg / day',
    description: 'Store vegetables and fruits safely',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 8,
    jobsCompleted: 2300,
    features: ['Temperature Control', 'Safe Storage', 'Transparent Pricing', 'Quick Access']
  },
  {
    id: 'warehouse-booking',
    title: 'Warehouse Booking',
    category: 'logistics',
    categoryEmoji: '🚛',
    price: '₹3 / bag / day',
    description: 'Secure grain storage',
    rating: 4.7,
    availability: 'Available Now',
    verified: true,
    providersNearby: 6,
    jobsCompleted: 1800,
    features: ['Secure Storage', 'No Damage', 'Insurance Available', 'Easy Access']
  },

  // Input Services
  {
    id: 'certified-seeds',
    title: 'Certified Seeds Delivery',
    category: 'inputs',
    categoryEmoji: '🛒',
    price: 'Starting ₹250',
    description: 'Quality seeds at doorstep',
    rating: 4.9,
    availability: 'Available Now',
    verified: true,
    providersNearby: 35,
    jobsCompleted: 8900,
    features: ['Govt Certified', 'High Germination', 'Free Delivery', 'Expert Guide']
  },
  {
    id: 'fertilizer-delivery',
    title: 'Fertilizer Delivery',
    category: 'inputs',
    categoryEmoji: '🛒',
    price: 'Market Price',
    description: 'Genuine fertilizers delivered',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 40,
    jobsCompleted: 12500,
    features: ['Authentic Products', 'Best Price', 'Home Delivery', 'Bulk Discount']
  },
  {
    id: 'pesticide-delivery',
    title: 'Pesticide Delivery',
    category: 'inputs',
    categoryEmoji: '🛒',
    price: 'Market Price',
    description: 'Approved crop protection products',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 38,
    jobsCompleted: 9800,
    features: ['Govt Approved', 'Expert Advice', 'Safe Handling', 'Usage Guide']
  },
  {
    id: 'organic-inputs',
    title: 'Organic Inputs',
    category: 'inputs',
    categoryEmoji: '🛒',
    price: 'Starting ₹199',
    description: 'Organic fertilizers and bio-products',
    rating: 4.8,
    availability: 'Available Now',
    verified: true,
    providersNearby: 25,
    jobsCompleted: 3400,
    features: ['Certified Organic', 'Eco Friendly', 'Premium Quality', 'Expert Tips']
  },

  // Infrastructure
  {
    id: 'farm-fencing',
    title: 'Farm Fencing',
    category: 'infrastructure',
    categoryEmoji: '🏡',
    price: 'Custom Quote',
    description: 'Wire fencing installation',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 5,
    jobsCompleted: 450,
    features: ['Durable Material', 'Professional Install', 'Weather Proof', 'Warranty']
  },
  {
    id: 'polyhouse',
    title: 'Polyhouse Construction',
    category: 'infrastructure',
    categoryEmoji: '🏡',
    price: 'Custom Quote',
    description: 'Protected cultivation setup',
    rating: 4.9,
    availability: 'Available Today',
    verified: true,
    providersNearby: 3,
    jobsCompleted: 280,
    features: ['Govt Subsidy', 'Climate Control', 'Expert Design', 'High Yield']
  },
  {
    id: 'greenhouse',
    title: 'Greenhouse Installation',
    category: 'infrastructure',
    categoryEmoji: '🏡',
    price: 'Custom Quote',
    description: 'Commercial greenhouse solutions',
    rating: 4.9,
    availability: 'Available Today',
    verified: true,
    providersNearby: 2,
    jobsCompleted: 120,
    features: ['Modern Design', 'Climate Control', 'Year-Round', 'High Tech']
  },
  {
    id: 'farm-pond',
    title: 'Farm Pond Construction',
    category: 'infrastructure',
    categoryEmoji: '🏡',
    price: 'Custom Quote',
    description: 'Rainwater harvesting ponds',
    rating: 4.8,
    availability: 'Available Today',
    verified: true,
    providersNearby: 4,
    jobsCompleted: 180,
    features: ['Govt Subsidy', 'Water Conservation', 'Expert Design', 'Durable']
  },
  {
    id: 'dairy-shed',
    title: 'Dairy Shed Construction',
    category: 'infrastructure',
    categoryEmoji: '🏡',
    price: 'Custom Quote',
    description: 'Modern livestock sheds',
    rating: 4.7,
    availability: 'Available Today',
    verified: true,
    providersNearby: 3,
    jobsCompleted: 95,
    features: ['Modern Design', 'Hygiene Focused', 'Ventilation', 'Expert Built']
  },
]
